name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  e2e_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flags: [ '', '-race' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Run docker containers
        run: make test-e2e-docker-up

      - name: E2E
        env:
          GOFLAGS: ${{ matrix.flags }}
          LOG_LEVEL: error
        run: make test-e2e

